python_env = "./env/bin/python3"
audio_file = "./misc/space.wav"
llm_model = "capybarahermes-2.5-mistral-7b.Q4_0:latest"
tts_model = "af_heart"
output = "./misc/llm-output.wav"
stt_model = "tiny"
stt_lang = "en"
log_file = "./logs/system.log"
enable_logging = true
